<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class ProvisionRecomendation extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('starting_provision_recomendations')->insert(
            array(
                // The Ruins (location_id 1)
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 1, 'recommended_amount' => 12),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 2, 'recommended_amount' => 2),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 5, 'recommended_amount' => 2),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 6, 'recommended_amount' => 3),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 7, 'recommended_amount' => 3),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 9, 'recommended_amount' => 8),
                array('location_id' => 1, 'location_length' => 1, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 1, 'recommended_amount' => 20),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 2, 'recommended_amount' => 3),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 5, 'recommended_amount' => 3),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 6, 'recommended_amount' => 4),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 7, 'recommended_amount' => 4),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 9, 'recommended_amount' => 12),
                array('location_id' => 1, 'location_length' => 2, 'provision_id' => 10, 'recommended_amount' => 1),

                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 1, 'recommended_amount' => 24),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 2, 'recommended_amount' => 4),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 5, 'recommended_amount' => 4),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 6, 'recommended_amount' => 5),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 7, 'recommended_amount' => 5),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 9, 'recommended_amount' => 16),
                array('location_id' => 1, 'location_length' => 3, 'provision_id' => 10, 'recommended_amount' => 2),

                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 1, 'location_length' => 4, 'provision_id' => 10, 'recommended_amount' => 0),


                //The Warrens (location_id 2)
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 1, 'recommended_amount' => 12),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 2, 'recommended_amount' => 2),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 4, 'recommended_amount' => 3),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 5, 'recommended_amount' => 3),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 6, 'recommended_amount' => 2),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 7, 'recommended_amount' => 3),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 9, 'recommended_amount' => 10),
                array('location_id' => 2, 'location_length' => 1, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 1, 'recommended_amount' => 18),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 2, 'recommended_amount' => 3),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 4, 'recommended_amount' => 3),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 5, 'recommended_amount' => 4),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 6, 'recommended_amount' => 3),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 7, 'recommended_amount' => 3),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 9, 'recommended_amount' => 16),
                array('location_id' => 2, 'location_length' => 2, 'provision_id' => 10, 'recommended_amount' => 1),

                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 1, 'recommended_amount' => 20),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 2, 'recommended_amount' => 4),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 4, 'recommended_amount' => 4),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 5, 'recommended_amount' => 5),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 6, 'recommended_amount' => 4),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 7, 'recommended_amount' => 4),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 9, 'recommended_amount' => 20),
                array('location_id' => 2, 'location_length' => 3, 'provision_id' => 10, 'recommended_amount' => 2),

                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 2, 'location_length' => 4, 'provision_id' => 10, 'recommended_amount' => 0),


                //The Weald (location_id 3)
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 1, 'recommended_amount' => 12),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 2, 'recommended_amount' => 4),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 3, 'recommended_amount' => 3),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 4, 'recommended_amount' => 2),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 5, 'recommended_amount' => 1),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 6, 'recommended_amount' => 2),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 7, 'recommended_amount' => 1),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 9, 'recommended_amount' => 8),
                array('location_id' => 3, 'location_length' => 1, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 1, 'recommended_amount' => 20),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 2, 'recommended_amount' => 5),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 3, 'recommended_amount' => 4),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 4, 'recommended_amount' => 3),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 5, 'recommended_amount' => 2),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 6, 'recommended_amount' => 3),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 7, 'recommended_amount' => 2),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 9, 'recommended_amount' => 12),
                array('location_id' => 3, 'location_length' => 2, 'provision_id' => 10, 'recommended_amount' => 1),

                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 1, 'recommended_amount' => 24),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 2, 'recommended_amount' => 6),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 3, 'recommended_amount' => 5),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 4, 'recommended_amount' => 4),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 5, 'recommended_amount' => 2),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 6, 'recommended_amount' => 4),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 7, 'recommended_amount' => 2),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 9, 'recommended_amount' => 16),
                array('location_id' => 3, 'location_length' => 3, 'provision_id' => 10, 'recommended_amount' => 2),

                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 3, 'location_length' => 4, 'provision_id' => 10, 'recommended_amount' => 0),

                //The Cove (location_id 4)
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 1, 'recommended_amount' => 12),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 2, 'recommended_amount' => 4),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 4, 'recommended_amount' => 2),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 5, 'recommended_amount' => 2),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 6, 'recommended_amount' => 2),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 9, 'recommended_amount' => 8),
                array('location_id' => 4, 'location_length' => 1, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 1, 'recommended_amount' => 20),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 2, 'recommended_amount' => 5),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 4, 'recommended_amount' => 4),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 5, 'recommended_amount' => 4),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 6, 'recommended_amount' => 3),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 9, 'recommended_amount' => 12),
                array('location_id' => 4, 'location_length' => 2, 'provision_id' => 10, 'recommended_amount' => 1),

                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 1, 'recommended_amount' => 24),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 2, 'recommended_amount' => 6),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 4, 'recommended_amount' => 6),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 5, 'recommended_amount' => 4),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 6, 'recommended_amount' => 4),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 9, 'recommended_amount' => 16),
                array('location_id' => 4, 'location_length' => 3, 'provision_id' => 10, 'recommended_amount' => 2),

                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 4, 'location_length' => 4, 'provision_id' => 10, 'recommended_amount' => 0),
                //Courtyard (location_id 5)
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 1, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 2, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 3, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 5, 'location_length' => 4, 'provision_id' => 10, 'recommended_amount' => 0),
                //Farmstead (location_id 6)
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 1, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 2, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 3, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 6, 'location_length' => 4, 'provision_id' => 10, 'recommended_amount' => 0),
                //The Darkest Dungeon (location_id 7)
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 1, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 2, 'provision_id' => 10, 'recommended_amount' => 0),

                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 3, 'provision_id' => 10, 'recommended_amount' => 0),
                
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 1, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 2, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 3, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 4, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 5, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 6, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 7, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 8, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 9, 'recommended_amount' => 0),
                array('location_id' => 7, 'location_length' => 4, 'provision_id' => 10, 'recommended_amount' => 0),
            )
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
